version: '3.8'

services:
  mongodb:
    image: mongo:latest
    # command: /bin/sh -c 'python3 main.py &'
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: